const NODE_SIZE_SMALL = 10;
const NODE_SIZE_MEDIUM = 20;
const NODE_SIZE_LARGE = 30;

export let NODE_PIXEL_SIZE = NODE_SIZE_LARGE;

if (window.innerWidth < 500) {
  NODE_PIXEL_SIZE = NODE_SIZE_SMALL;
} else if (window.innerWidth < 1000) {
  NODE_PIXEL_SIZE = NODE_SIZE_MEDIUM;
} else {
  NODE_PIXEL_SIZE = NODE_SIZE_LARGE;
}

const WIDTH_PER_WINDOW_WIDTH_SMALL = 90;
const HEIGHT_PER_WINDOW_HEIGHT_SMALL = 90;

const WIDTH_PER_WINDOW_WIDTH_MEDIUM = 80;
const HEIGHT_PER_WINDOW_HEIGHT_MEDIUM = 80;

const WIDTH_PER_WINDOW_WIDTH_LARGE = 70;
const HEIGHT_PER_WINDOW_HEIGHT_LARGE = 70;

export const WIDTH_PER_WINDOW_WIDTH =
  window.innerWidth < 500
    ? WIDTH_PER_WINDOW_WIDTH_SMALL
    : window.innerWidth < 1000
    ? WIDTH_PER_WINDOW_WIDTH_MEDIUM
    : WIDTH_PER_WINDOW_WIDTH_LARGE;

export const HEIGHT_PER_WINDOW_HEIGHT =
  window.innerWidth < 500
    ? HEIGHT_PER_WINDOW_HEIGHT_SMALL
    : window.innerWidth < 1000
    ? HEIGHT_PER_WINDOW_HEIGHT_MEDIUM
    : HEIGHT_PER_WINDOW_HEIGHT_LARGE;

export const SIDEBAR_WIDTH = 380;
export const DELTA_SENSITIVITY = 0.25;

export const SIDEBAR_MIN_WIDTH = 300;
export const SIDEBAR_MAX_WIDTH = 500;
